# Generated by Django 5.2.4 on 2025-07-25 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do cliente')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('source', models.CharField(choices=[('website', 'Google / Site'), ('referral', 'Indicação'), ('social', 'Mídia Social'), ('ads', 'Anúncio Pago'), ('event', 'Evento / Feira'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Origem')),
                ('service_type', models.CharField(blank=True, choices=[('opening', 'Abertura de empresa'), ('accounting', 'Contabilidade mensal'), ('ending', 'Encerramento de empresa'), ('change_accountant', 'Troca de contador'), ('simples', 'Regularização no Simples Nacional'), ('payroll', 'Folha de pagamento'), ('invoices', 'Emissão de notas fiscais'), ('consulting', 'Consultoria fiscal ou tributária'), ('planning', 'Planejamento tributário'), ('other', 'Outro')], max_length=30, null=True, verbose_name='Tipo de serviço')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
