# Generated by Django 5.2.4 on 2025-07-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_service_type_alter_client_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='source',
        ),
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
