# Generated by Django 5.2.4 on 2025-07-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRManager', '0002_lead_phone_lead_service_type_lead_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_to_client',
            field=models.BooleanField(default=False),
        ),
    ]
